apps/book/urls.py
from django.urls import path
from django.conf.urls import url,include
from .views import Index,searchbus,searchflight,searchtrain,booknow,checkout,confirmation,accountdetail,paytmresponse
app_name="bookin"
urlpatterns=[
    path('',Index.as_view(),name='index'),
    path('search-bus/',searchbus,name='bus-search'),
    path('search-train/',searchtrain,name='train-search'),
    path('search-flight/',searchflight,name='flight-search'),
    path('booknow/<int:pk>',booknow,name='booknow'),
    path('checkout/<str:pnr_id>',checkout,name='checkout'),
    path('confrimations/<str:statuss>/',confirmation,name='confirmation'),
    path('acountdetail/', accountdetail, name='accountDetail'),
    path('paytmresponse/',paytmresponse,name='paytmresponse'),


            ]

travellite/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

from cms.sitemaps import CMSSitemap
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.static import serve
from apps.book.views import loginPage,registerPage,logoutpage
from django.urls import path
admin.autodiscover()

urlpatterns = [
    url(r'^sitemap\.xml$', sitemap,
        {'sitemaps': {'cmspages': CMSSitemap}}),
]

urlpatterns += i18n_patterns(
        url(r'^admin/', admin.site.urls),  # NOQA
        url(r'^trial/', include('apps.book.urls')),
        url(r'^api/', include('apps.api.urls')),

        path('login/', loginPage, name='loginPage'),
        path('logout/', logoutpage, name='logoutPage'),
        path('register/', registerPage, name='registerPage'),
        url(r'^', include('cms.urls')),

)

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns = [
        url(r'^media/(?P<path>.*)$', serve,
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        ] + staticfiles_urlpatterns() + urlpatterns

apps/book/models.py
from django.db import models
from django.contrib.auth.models import User

from django.utils import timezone


# Create your models here.
day_choice=[('MON','MON'),('TUE','TUE'),('WED','WED'),('THU','THU'),('FRI','FRI'),('SAT','SAT'),('SUN','SUN')]
class Location(models.Model):
    city_name=models.CharField(max_length=26)

    def __str__(self):
        return self.city_name


class Flight(models.Model):
        flight_name=models.CharField(max_length=30)
        source=models.ForeignKey(Location,related_name='flight_sources',on_delete=models.CASCADE)
        destination = models.ForeignKey(Location, related_name='flight_destination', on_delete=models.CASCADE)
        day=models.CharField(choices=day_choice,max_length=5)

        def __str__(self):
            return self.flight_name


class Bus(models.Model):
    bus_name = models.CharField(max_length=30)
    source = models.ForeignKey(Location, related_name='bus_sources', on_delete=models.CASCADE)
    destination = models.ForeignKey(Location, related_name='bus_destination', on_delete=models.CASCADE)
    day = models.CharField(choices=day_choice, max_length=5)

    def __str__(self):
        return self.bus_name

class Train(models.Model):
        train_name = models.CharField(max_length=30)
        source = models.ForeignKey(Location, related_name='train_sources', on_delete=models.CASCADE)
        destination = models.ForeignKey(Location, related_name='train_destination', on_delete=models.CASCADE)
        day = models.CharField(choices=day_choice, max_length=5)

        def __str__(self):
            return self.train_name

class TrainFare(models.Model):
    class_choice=[['1','1AC'],['2','2AC'],['3','3AC'],['4','SL']]
    name=models.ForeignKey(Train,related_name='trains',on_delete=models.CASCADE)
    category=models.CharField(choices=class_choice,max_length=5)
    fare=models.FloatField()

    def __str__(self):
        return self.name.train_name


class FlightFare(models.Model):
    class_choice = [('1', 'Business'), ('2', 'First Class'), ('3', 'economy')]
    name = models.ForeignKey(Flight, related_name='flights', on_delete=models.CASCADE)
    category = models.CharField(choices=class_choice, max_length=5)
    fare = models.FloatField()

    def __str__(self):
        return self.name.flight_name


class BusFare(models.Model):
    class_choice = [('1', 'AC'), ('2', 'NON-AC')]
    name = models.ForeignKey(Bus, related_name='buses', on_delete=models.CASCADE)
    category = models.CharField(choices=class_choice, max_length=5)
    fare = models.FloatField()

    def __str__(self):
        return self.name.bus_name


class BookTrain(models.Model):
    user_name=models.ForeignKey(User,on_delete=models.CASCADE)
    book_type=models.ForeignKey(TrainFare,on_delete=models.CASCADE)
    pnrno = models.CharField(max_length=10,unique=True)
    status=models.BooleanField(default=0)
    def __str__(self):
        return self.pnrno


class Passenger(models.Model):

    name=models.CharField(max_length=26)
    age=models.IntegerField()
    book_train=models.ForeignKey(BookTrain,on_delete=models.CASCADE)
    def __str__(self):
        return self.name

class Traincheckout(models.Model):
    pnr_no=models.ForeignKey(BookTrain,on_delete=models.CASCADE)
    totalfare=models.FloatField()
    user_name = models.ForeignKey(User, on_delete=models.CASCADE)
    def __str__(self):
        return self.pnr_no.pnrno

class BookFlight(models.Model):
    user_name = models.ForeignKey(User, on_delete=models.CASCADE)
    book_type = models.ForeignKey(FlightFare, on_delete=models.CASCADE)

    def __str__(self):
        return self.user_name.username
class BookBus(models.Model):
    user_name=models.ForeignKey(User,on_delete=models.CASCADE)
    book_type=models.ForeignKey(BusFare,on_delete=models.CASCADE)

    def __str__(self):
        return self.user_name.username

apps/book/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import Train,Bus,Flight,TrainFare

class TrainSearch(forms.ModelForm):
    class Meta:
        model=Train
        fields=['source','destination','day']


class FlightSearch(forms.ModelForm):
    class Meta:
        model = Flight
        fields = ['source', 'destination', 'day']


class BusSearch(forms.ModelForm):
    class Meta:
        model = Bus
        fields = ['source', 'destination', 'day']


class TrainFareForm(forms.ModelForm):
    class Meta:
        model=TrainFare
        fields=['category']

class CreateUser(UserCreationForm):
    class Meta:
        model=User
        fields=['username','email','password1','password2']

apps/book/views.py
from .models import *
from.forms import BusSearch,TrainSearch,FlightSearch,CreateUser
from django.views.generic import TemplateView
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm
import json
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt,csrf_protect
from apps.api.serializers import *
import requests
from random import randint
from django.forms import inlineformset_factory
from django.core import serializers
from django.contrib import messages
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from apps.paytm import PaytmChecksum

from django.conf import settings
from django.http.response import HttpResponse
# Create your views here.
class Index(TemplateView):
    template_name = 'index.html'
def searchbus(request):
    form=BusSearch()

    context={
        'form':form,
        'user':request.user,
    }
    if request.method=='GET':
        form=BusSearch(request.GET)
        if form.is_valid():
            result=Bus.objects.filter(source__city_name__icontains=form.cleaned_data['source']).filter(destination__city_name__icontains=form.cleaned_data['destination']).filter(day=form.cleaned_data['day'])

            context['result']=result
        return render(request,'searchbus.html',context)
def searchtrain(request):
    form=TrainSearch()
    context={
        'form':form
    }
    if request.method=='GET':
        form=TrainSearch(request.GET)
        if form.is_valid():
            result=Train.objects.filter(source__city_name__icontains=form.cleaned_data['source']).filter(destination__city_name__icontains=form.cleaned_data['destination']).filter(day=form.cleaned_data['day'])
            a=request.GET['source']
            ans=TrainFare.objects.filter(name__source_id=a)
            option=TrainFare.class_choice
            context['option']=option
            context['result']=result
            a1=request.GET.get('aditya')
            context['a1']=a1
            print(a1)
        return render(request,'searchtrain.html',context)

def searchflight(request):
    form=FlightSearch()
    context={
        'form':form
    }
    if request.method=='GET':
        form=FlightSearch(request.GET)
        if form.is_valid():
            result=Flight.objects.filter(source__city_name__icontains=form.cleaned_data['source']).filter(destination__city_name__icontains=form.cleaned_data['destination']).filter(day=form.cleaned_data['day'])

            context['result']=result
        return render(request,'searchflight.html',context)


def loginPage(request):
    if request.method=='POST':
        username=request.POST.get('username')
        password=request.POST.get('password')
        user=authenticate(request,username=username,password=password)
        if user is not None:
            login(request,user)
            return redirect("/")
        else:
            messages.info(request,'Username or password is incorrect')
    context={}
    return render(request, 'login.html', context)
def logoutpage(request):
    logout(request)
    return redirect('/')

def registerPage(request):
    if request.user.is_authenticated:
        return redirect('/')
    else:
        form=CreateUser
        cust={}
        if request.method=='POST':
            form=CreateUser(request.POST)
            if form.is_valid():
                form.save()
                user=form.cleaned_data.get('username')
                messages.success(request,user+' created successfully')
                return redirect('loginPage')
        context={
                    'form':form,
                }
        return render(request, 'register.html', context)
@csrf_exempt
def booknow(request,pk):
    url="http://127.0.0.1:8000/en/api/trainfare_list/"+str(pk)
    ans=requests.get(url=url).json()
    train_name=Train.objects.filter(id=ans[0]['name'])
    context={'trainname':train_name,'fare':ans[0]['fare'],'category':ans[0]['category']}
    PassengerFormSet = inlineformset_factory(BookTrain, Passenger, fields=('name', 'age'))
    formset = PassengerFormSet()
    context['form'] = formset
    if request.method=='POST':
        uniqueno = pnrgen()
        print(uniqueno)
        BookTrain.objects.create(
            user_name=request.user,
            book_type_id=pk,
            pnrno=uniqueno,
        )
        urll = "http://127.0.0.1:8000/en/api/booktrain_list/?pnrno=" + str(uniqueno)
        booktrainid = requests.get(url=urll).json()
        exp = BookTrain.objects.get(pk=booktrainid[0]['id'])
        context['pnrno'] = booktrainid[0]['pnrno']
        formset=PassengerFormSet(request.POST,instance=exp)
        if formset.is_valid():
            formset.save()
            return redirect('bookin:checkout',pnr_id=booktrainid[0]['pnrno'])
    return render(request,'book.html',context)


def checkout(request,pnr_id):
    passenger=Passenger.objects.filter(book_train__pnrno__contains=pnr_id).values_list('name',flat=True)
    trainname=Train.objects.get(trains__booktrain__pnrno__contains=pnr_id)

    trainfare=TrainFare.objects.filter(booktrain__pnrno__contains=pnr_id).values_list('fare',flat=True)

    traincategory=TrainFare.objects.filter(booktrain__pnrno__contains=pnr_id).values_list('category',flat=True)


    source=Location.objects.get(train_sources__train_name__contains=trainname)

    destination = Location.objects.get(train_destination__train_name__contains=trainname)

    context={
        'trainname':trainname,'source':source,'destination':destination,'traincategory':traincategory[0],
        'totalfare':trainfare[0]*passenger.count(),'passenger':passenger,'pnr':pnr_id
    }
    urll = "http://127.0.0.1:8000/en/api/booktrain_list/?pnrno=" + str(pnr_id)
    booktrainid = requests.get(url=urll).json()
    Traincheckout.objects.create(
        pnr_no_id=booktrainid[0]['id'],
        totalfare=trainfare[0]*passenger.count(),
        user_name=request.user,
    )


    return render(request,'checkoutpage.html',context)

def confirmation(request,statuss):

    tt=BookTrain.objects.filter(pnrno=statuss).filter(user_name_id=request.user.id).values_list('id',flat=True)
    fare=Traincheckout.objects.filter(pnr_no_id=tt[0]).values_list('totalfare')


    # import checksum generation utility
    # You can get this utility from https://developer.paytm.com/docs/checksum/


    paytmParams = dict()

    paytmParams["body"] = {
        "requestType": "Payment",
        "mid": settings.PAYTM_MERCHANT_ID,
        "websiteName": "WEBSTAGING",
        "orderId": statuss,
        "callbackUrl": settings.PAYTM_CALLBACK_URL,
        "txnAmount": {
            "value": str(fare[0][0]),
            "currency": "INR",
        },
        "userInfo": {
            "custId": request.user.username,
        },
    }

    # Generate checksum by parameters we have in body
    # Find your Merchant Key in your Paytm Dashboard at https://dashboard.paytm.com/next/apikeys
    checksum = PaytmChecksum.generateSignature(json.dumps(paytmParams["body"]),settings.PAYTM_MERCHANT_KEY)

    paytmParams["head"] = {
        "signature": checksum
    }

    post_data = json.dumps(paytmParams)

    # for Staging
    url = "https://securegw-stage.paytm.in/theia/api/v1/initiateTransaction?mid="+settings.PAYTM_MERCHANT_ID+"&orderId="+statuss
    print(url)

    # for Production
    # url = "https://securegw.paytm.in/theia/api/v1/initiateTransaction?mid=YOUR_MID_HERE&orderId=ORDERID_98765"
    response = requests.post(url, data=post_data, headers={"Content-type": "application/json"})
    resp=response.json()
    context={
        'payment_url':settings.PAYTM_PAYMENT_GATEWAY_URL,
        'mid':settings.PAYTM_MERCHANT_ID,
        'order_id':statuss,
        'txntoken':resp['body']['txnToken'],
        'CHECKSUMHASH':resp['head']['signature'],
        'amount':'1.00',
        'website':settings.PAYTM_WEBSITE

    }
    return  render(request,'confirmation_page.html',context)


def accountdetail(request):
    history=Traincheckout.objects.filter(user_name=request.user)
    return render(request,'accounts_detail.html',{'history':history})

@csrf_exempt
def paytmresponse(request):
    order_id=''
    mid_id=''
    checksumm=''
    res_dict={}
    responseparams=request.POST
    for i in responseparams.keys():
        res_dict[i]=responseparams[i]
        if i=='ORDERID':
          order_id=responseparams[i]
        if i=='MID':
           mid_id=responseparams[i]
        if i=='CHECKSUMHASH':
            checksumm=responseparams[i]


    paytmParams = dict()

    paytmParams["MID"] = settings.PAYTM_MERCHANT_ID
    paytmParams["ORDERID"] = order_id

    # Generate checksum by parameters we have
    # Find your Merchant Key in your Paytm Dashboard at https://dashboard.paytm.com/next/apikeys
    checksum = PaytmChecksum.generateSignature(paytmParams, settings.PAYTM_MERCHANT_KEY)

    paytmParams["CHECKSUMHASH"] = checksumm

    post_data = json.dumps(paytmParams)

    # for Staging
    url = "https://securegw-stage.paytm.in/order/status"

    # for Production
    # url = "https://securegw.paytm.in/order/status"

    response = requests.post(url, data=post_data, headers={"Content-type": "application/json"}).json()
    print('response=',response)
    print('res_dict=',response)
    isVerifySignature = PaytmChecksum.verifySignature(paytmParams, settings.PAYTM_MERCHANT_KEY,checksum)
    context={}
    if isVerifySignature:
        context={'msg':'PAYEMNT SUCCESSFUL','orderid':order_id}

    else:
        context={'msg':'PAYMENT FAILED CONTACT US IF MONEY IS DEDUCTED','orderid':order_id}

    return render(request,'receipt.html',context)

def pnrgen():
    pnr=BookTrain.objects.values_list('pnrno',flat=True)
    num=randint(1,100000)
    flag=1

    while flag==1:
        if num  in pnr:
            num = randint(1, 100000)
        else:
            flag=0
            break
    return num

apps/book/templates/accounts_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Accounts</title>
</head>
<body>
<h1>welcome to transaction History</h1>
{% for his in history %}
    {{ his.totalfare }}<br>
    {{ his.pnr_no }}
{% endfor %}
</body>
</html>

apps/book/templates/book.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>BookingDetails</title>
</head>
<body>


{% for i in trainname %}
   TRAIN NAME: {{ i.train_name }}<hr>
    source:{{ i.source }}<hr>
    Destination:{{ i.destination }}<hr>

{% endfor %}
FARE:{{ fare }}<hr>
CATEGORY:{{ category }}<hr>

<form method="POST">
    {% csrf_token %}
    {{ form }}
    <button class="btn btn-primary"  type="submit" >Continue</button>
</form>
<script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>

</body>
</html>

apps/book/templates/checkoutpage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Checkout</title>
</head>
<body>
<p>
Train name:{{ trainname }}<hr>
Source:{{ source }}  destination:{{ destination }}<hr>
category:{{ traincategory }}   total fare:{{ totalfare }}<hr>


<h1>Passenger details</h1><hr>
{% for i in passenger %}
    {{ i }}<br>
{% endfor %}
</p>
<a class="btn btn-primary" type="button" href="{% url 'bookin:confirmation' statuss=pnr %}">BOOK</a>
</body>
</html>

apps/book/templates/confirmation_page.html
{{ fare }}
<html>
   <head>
      <title>Show Payment Page</title>
   </head>
   <body>
      <center>
         <h1>Please do not refresh this page...</h1>
      </center>
      <form method="post" action="{{ payment_url }}"  name="paytm">
         <table border="1">
            <tbody>
               <input type="hidden" name="mid" value="{{ mid }}">
               <input type="hidden" name="orderId" value="{{ order_id }}">
               <input type="hidden" name="txnToken" value="{{ txntoken }}">
                  <input type="hidden" name="CHECKSUMHASH" value="{{ CHECKSUMHASH }}">
                  <input type="hidden" name="TXN_AMOUNT" value="{{ amount }}">
             <input type="hidden" name="WEBSITE" value="{{ website }}">
            </tbody>
         </table>
         <script type="text/javascript"> document.paytm.submit(); </script>
      </form>
   </body>

apps/book/templates/index.html
<a href="{% url 'bookin:bus-search' %}">searchbus</a>
<a href="{% url 'bookin:train-search' %}">searchtrain</a>
<a href="{% url 'bookin:flight-search' %}">searchflight</a>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.1/css/bootstrap.min.css" integrity="sha384-VCmXjywReHh4PwowAiWNagnWcLhlEJLA5buUprzK8rxFgeH0kww/aWY76TfkUoSX" crossorigin="anonymous">

apps/book/templates/receipt.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

apps/book/templates/searchbus.html
{{ user }}

apps/book/templates/searchflight.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.1/css/bootstrap.min.css" integrity="sha384-VCmXjywReHh4PwowAiWNagnWcLhlEJLA5buUprzK8rxFgeH0kww/aWY76TfkUoSX" crossorigin="anonymous">
</head>
<body>
{{ requst.user }}
<form method="GET">
    {{ form.as_table }}
<button type="submit" class="btn btn-primary">search</button>
</form>
{% if result.count == 0 %}
    <h1>invalid search</h1>
    {% else %}
    {% for i in result %}
        <strong>{{ i.flight_name }}</strong>
        {{ i.source }}
        {{ i.destination }}
    {% endfor %}
{% endif %}
</body>
</html>

apps/book/templates/searchtrain.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>SEARCH Train</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>

<div class="container bg-info">
    <h1>Welcome to Travellite Buddy</h1>
<h3>enter the details</h3>
<form method="GET">
    {{ form.as_table}}
<button type="submit" class="btn btn-primary">search</button>
</form>
</div>
<br>
<hr>
<h1 class="container bg-info">TRAIN LIST</h1>
{% if result.count == 0 %}
    <h1 class="container">invalid search</h1>
    {% else %}

    <div class=" container justify-content-center bg-transparent">
    {% for i in result %}
        <strong >{{ i.train_name }}</strong>
        {{ i.source }}
        {{ i.destination }}
        <div id="why">
        <select id='aditya'  onchange="get_fare(this.value,{{ i.id }})">
        <option value="-1" >---</option>
        <option value="1" >1ac</option>
        <option value="2" >2ac</option>
        <option value="3">3ac</option>
        <option value="4" >sl</option>
        </select>
        <p id='{{ i.id }}' >

        </p>
        <br>
        </div>

    {% endfor %}
{% endif %}
</div>
<script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
<script>
function get_fare(category,id) {
    let param = 'category='+category + '&name='+id;
    send_request(param,id);

  }

  function send_request(param,id) {
    function f(e){
        e.preventDefault();
    }

    $.ajax({
        method:"GET",
        url:"http://127.0.0.1:8000/en/api/trainfare_list/?"+param,
        success:function (data) {
           update_table(data,id);
        }
    });

  }
   function update_table(data,id) {

       let row;
       let temp = id;
       let all_rows = '';
       if (Object.keys(data).length > 0) {
           Object.keys(data).forEach(key => {
               elem = data[key];
               row = elem['fare'];
               all_rows = all_rows + row;

               document.getElementById(temp).innerHTML = elem['fare'];
               send_msg(elem['id'],elem['fare'],id)

           });


       } else {
           row = 'unavailable';
           all_rows = all_rows + row;
           document.getElementById(temp).innerText = 'unavailabe';


       }

   }
function send_msg(pk,fare,id) {
    alert(pk);
     var urll= "{% url 'bookin:booknow' pk=0 %}".replace(/0/,pk);

    document.getElementById(id).innerHTML=fare+`<a class='btn btn-primary' id='book_now'>book</a>`;
    document.getElementById('book_now').setAttribute("href",urll);
}


</script>
</body>
</html>